# Redirect all HTTP traffic to HTTPS www
server {
    listen 80;
    server_name tutoriasuniversitarias.com www.tutoriasuniversitarias.com;
    
    # Preserve ACME challenge location
    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        auth_request off;
        allow all;
        root /usr/share/nginx/html;
        try_files $uri =404;
        break;
    }
    
    location / {
        return 301 https://www.tutoriasuniversitarias.com$request_uri;
    }
}

# Redirect HTTPS non-www to www
server {
    listen 443 ssl http2;
    server_name tutoriasuniversitarias.com;
    ssl_certificate /etc/nginx/certs/tutoriasuniversitarias.com.crt;
    ssl_certificate_key /etc/nginx/certs/tutoriasuniversitarias.com.key;
    return 301 https://www.tutoriasuniversitarias.com$request_uri;
}

# Handle HTTPS www requests
server {
    listen 443 ssl http2;
    server_name www.tutoriasuniversitarias.com;
    ssl_certificate /etc/nginx/certs/www.tutoriasuniversitarias.com.crt;
    ssl_certificate_key /etc/nginx/certs/www.tutoriasuniversitarias.com.key;
    
    location / {
        proxy_pass http://www.tutoriasuniversitarias.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}