# Redirect all HTTP traffic to HTTPS www
server {
    listen 80;
    server_name tutoriasuniversitarias.com www.tutoriasuniversitarias.com;
    
    # Preserve ACME challenge location
    location ^~ /.well-known/acme-challenge/ {
        auth_basic off;
        auth_request off;
        allow all;
        root /usr/share/nginx/html;
        try_files $uri =404;
        break;
    }
    
    location / {
        return 301 https://www.tutoriasuniversitarias.com$request_uri;
    }
}

# Redirect HTTPS non-www to www
server {
    listen 443 ssl;
    server_name tutoriasuniversitarias.com;
    
    ssl_certificate /etc/nginx/certs/tutoriasuniversitarias.com.crt;
    ssl_certificate_key /etc/nginx/certs/tutoriasuniversitarias.com.key;
    
    return 301 https://www.tutoriasuniversitarias.com$request_uri;
}